### ISSUE TITLE
rake is not working

### ISSUE THREAD

**Issue by tschimbr** [eonum/medlang#13]
When I checkout the project and try `rake test`or `rake -T`I encounter the following error:

```
rake aborted!
LoadError: cannot load such file -- /home/tim/medlang/lib/tasks/seed_helpers.rb
/home/tim/medlang/lib/tasks/db.rake:1:in `require_relative'
/home/tim/medlang/lib/tasks/db.rake:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/engine.rb:658:in `load'
/usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/engine.rb:658:in `each'
/usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/engine.rb:658:in `run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/application.rb:452:in `run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/engine.rb:453:in `load_tasks'
/home/tim/medlang/Rakefile:6:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by SamJa** [comment]
When I run rake test it works... but i get a bunch of error messages:
```
Finished in 0.027901s, 501.7706 runs/s, 0.0000 assertions/s.

  1) Error:
UsersControllerTest#test_should_create_user:
NoMethodError: undefined method `users' for #<UsersControllerTest:0x00000001fc4be8>
    test/controllers/users_controller_test.rb:5:in `block in <class:UsersControllerTest>'


  2) Error:
UsersControllerTest#test_should_destroy_user:
NoMethodError: undefined method `users' for #<UsersControllerTest:0x00000004bd27d0>
    test/controllers/users_controller_test.rb:5:in `block in <class:UsersControllerTest>'


  3) Error:
UsersControllerTest#test_should_get_edit:
NoMethodError: undefined method `users' for #<UsersControllerTest:0x00000004bd0bb0>
    test/controllers/users_controller_test.rb:5:in `block in <class:UsersControllerTest>'


  4) Error:
UsersControllerTest#test_should_get_index:
NoMethodError: undefined method `users' for #<UsersControllerTest:0x000000057fe2e8>
    test/controllers/users_controller_test.rb:5:in `block in <class:UsersControllerTest>'


  5) Error:
UsersControllerTest#test_should_get_new:
NoMethodError: undefined method `users' for #<UsersContrMaybe it works if you follow the the instructions in the new README.ollerTest:0x000000057f58a0>
    test/controllers/users_controller_test.rb:5:in `block in <class:UsersControllerTest>'


  6) Error:
UsersControllerTest#test_should_show_user:
NoMethodError: undefined method `users' for #<UsersControllerTest:0x000000057ed3a8>
    test/controllers/users_controller_test.rb:5:in `block in <class:UsersControllerTest>'


  7) Error:
UsersControllerTest#test_should_update_user:
NoMethodError: undefined method `users' for #<UsersControllerTest:0x000000057e4ff0>
    test/controllers/users_controller_test.rb:5:in `block in <class:UsersControllerTest>'


  8) Error:
LearnSessionsControllerTest#test_should_create_learn_session:
NoMethodError: undefined method `learn_sessions' for #<LearnSessionsControllerTest:0x000000057a34b0>
    test/controllers/learn_sessions_controller_test.rb:5:in `block in <class:LearnSessionsControllerTest>'


  9) Error:
LearnSessionsControllerTest#test_should_destroy_learn_session:
NoMethodError: undefined method `learn_sessions' for #<LearnSessionsControllerTest:0x000000056f1580>
    test/controllers/learn_sessions_controller_test.rb:5:in `block in <class:LearnSessionsControllerTest>'


 10) Error:
LearnSessionsControllerTest#test_should_get_edit:
NoMethodError: undefined method `learn_sessions' for #<LearnSessionsControllerTest:0x000000056e2508>
    test/controllers/learn_sessions_controller_test.rb:5:in `block in <class:LearnSessionsControllerTest>'


 11) Error:
LearnSessionsControllerTest#test_should_get_index:
NoMethodError: undefined method `learn_sessions' for #<LearnSessionsControllerTest:0x000000056d3260>
    test/controllers/learn_sessions_controller_test.rb:5:in `block in <class:LearnSessionsControllerTest>'


 12) Error:
LearnSessionsControllerTest#test_should_get_new:
NoMethodError: undefined method `learn_sessions' for #<LearnSessionsControllerTest:0x000000056c7f78>
    test/controllers/learn_sessions_controller_test.rb:5:in `block in <class:LearnSessionsControllerTest>'


 13) Error:
LearnSessionsControllerTest#test_should_show_learn_session:
NoMethodError: undefined method `learn_sessions' for #<LearnSessionsControllerTest:0x000000056c43c8>
    test/controllers/learn_sessions_controller_test.rb:5:in `block in <class:LearnSessionsControllerTest>'


 14) Error:
LearnSessionsControllerTest#test_should_update_learn_session:
NoMethodError: undefined method `learn_sessions' for #<LearnSessionsControllerTest:0x000000056b8f00>
    test/controllers/learn_sessions_controller_test.rb:5:in `block in <class:LearnSessionsControllerTest>'

14 runs, 0 assertions, 0 failures, 14 errors, 0 skips
```
Maybe it works if you follow the the instructions in the new README.
